plugins {
    alias(libs.plugins.kotlin.jvm)
}
//FIXME  must fix version use old javacv !!
group = 'org.bytedeco.javacv'
version = '1.5.12'
description = 'demo'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

sourceSets {
    main {
        java {
            srcDir files('../../javacv/samples')
            include 'RealSense2DepthMeasuring.java'
        }
        resources {
            srcDir files('../../javacv/samples')
            includes = [""]
        }
    }
}

tasks.register('run', JavaExec) {
    group = "application"
    description = "Runs the RealSense2DepthMeasuring main method"

    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'RealSense2DepthMeasuring'
    workingDir = rootProject.file("samples")
}

//FIXME  must fix version use old javacv !!
dependencies {

    implementation(libs.org.bytedeco.javacv.platform)
    implementation(libs.org.bytedeco.opencv.platform.gpu)
    implementation(libs.org.bytedeco.ffmpeg.platform.gpl)

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}
